name: Update UI Project Submodule

on:
  push:
    branches: 
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout UI Project Repository
      uses: actions/checkout@v2
      with:
        repository: 'aswinckr/aswin.design'
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: 'ui-project'

    - name: Update Submodule
      run: |
        cd ui-project/data/blog
        git pull origin main
        cd ../../
        git config user.name "aswinckr"
        git config user.email "your-email@example.com"
        git add data/blog
        git commit -m "Update data submodule to latest from aswin-design-data"
        git push
